name: Feature request
description: Suggest an enhancement aligned with the paper or deployment goals.
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an improvement!
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What would you like to see added or improved?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation / use case
      description: Why is this important? Include expected graph sizes or workloads if relevant.
    validations:
      required: true
  - type: textarea
    id: paper_context
    attributes:
      label: Paper alignment
      description: If applicable, reference the relevant section/lemma from the paper.
      placeholder: Section 5 dynamic spanners / Lemma 4.9 stability
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any existing workarounds or alternatives you've tried.
